services:
  - type: worker
    name: qora-bot
    runtime: node
    plan: starter
    rootDir: qora-bot
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
