const crypto = require("crypto");

const TelegramLinkCode = require("../models/TelegramLinkCode");
const { env } = require("../config/env");
const ApiError = require("../utils/ApiError");
const logger = require("../utils/logger");

const LINK_CODE_EXPIRES_MINUTES = 10;
const TELEGRAM_API_BASE = "https://api.telegram.org";

const isTelegramConfigured = () => Boolean(env.telegramBotToken);

const sendTelegramMessage = async (chatId, text) => {
  if (!isTelegramConfigured()) {
    throw new Error("Telegram bot is not configured");
  }

  const response = await fetch(`${TELEGRAM_API_BASE}/bot${env.telegramBotToken}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: chatId, text }),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => "");
    logger.error("telegram_send_message_failed", {
      status: response.status,
      message: errorText.slice(0, 300),
    });
    throw new Error(`Telegram sendMessage failed with status ${response.status}`);
  }

  return response.json();
};

const createLinkCode = async () => {
  if (!isTelegramConfigured()) {
    throw new ApiError(503, "Telegram login is not configured");
  }

  const code = crypto.randomBytes(6).toString("hex");
  const expiresAt = new Date(Date.now() + LINK_CODE_EXPIRES_MINUTES * 60 * 1000);

  await TelegramLinkCode.create({ code, expiresAt });

  return {
    code,
    expiresAt,
    botUsername: env.telegramBotUsername,
    deepLink: env.telegramBotUsername ? `https://t.me/${env.telegramBotUsername}?start=${code}` : null,
  };
};

const getLinkStatus = async (code) => {
  const record = await TelegramLinkCode.findOne({ code });

  if (!record || record.expiresAt < new Date()) {
    throw new ApiError(404, "Link code expired or not found");
  }

  return {
    linked: record.linked,
    identity: record.linked ? `tg:${record.chatId}` : null,
    telegramUsername: record.telegramUsername,
  };
};

// Called by the Telegram webhook whenever the bot receives an update. We only
// care about "/start <code>" messages sent right after the user taps the
// deep link generated by createLinkCode.
const handleTelegramUpdate = async (update) => {
  const message = update?.message;
  const text = message?.text;
  const chat = message?.chat;

  if (!text || !chat || !text.startsWith("/start")) {
    return;
  }

  const code = text.replace("/start", "").trim();
  if (!code) {
    return;
  }

  const record = await TelegramLinkCode.findOne({ code });
  if (!record || record.expiresAt < new Date()) {
    await sendTelegramMessage(chat.id, "Bu havola muddati o'tgan. Ilovada qaytadan urinib ko'ring.").catch(() => {});
    return;
  }

  record.chatId = String(chat.id);
  record.telegramUsername = chat.username || null;
  record.linked = true;
  await record.save();

  await sendTelegramMessage(
    chat.id,
    "Telegram akkauntingiz Stugram ilovasiga bog'landi. Endi ilovaga qaytib davom eting."
  ).catch(() => {});
};

module.exports = {
  isTelegramConfigured,
  sendTelegramMessage,
  createLinkCode,
  getLinkStatus,
  handleTelegramUpdate,
};
